name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checking out
        uses: actions/checkout@v4
      - name: Installing python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Installing pip
        run: python -m pip install --upgrade pip
      - name: Installing all dependencies [requirements.txt]
        run: pip install -r requirements.txt