name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    env:
      DATABASE_HOSTNAME: postgres
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: password17
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: 09dlajkdlkssdfdaduhkajdnfnadkhadhfikasdjhasdklfjkldd
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    runs-on: ubuntu-latest
    steps:
      - name: checking out
        uses: actions/checkout@v4
      - name: Installing python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Installing pip
        run: python -m pip install --upgrade pip
      - name: Installing all dependencies [requirements.txt]
        run: pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          pytest